import {Montserrat } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { LoaderProvider } from "@/context/Loader";
import Loader from "@/components/load";
import ContentWrapper from "@/components/ContentWrapper";

const MontserratFont = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${MontserratFont.variable} antialiased`}
      >
        <LoaderProvider>
        <Loader />
        <ContentWrapper>
           <Header />
        {children}
        <Footer />
        </ContentWrapper>
        </LoaderProvider>
       
      </body>
    </html>
  );
}
